create table if not exists invoice
(
    id                            serial primary key,
    driver_id                     integer,
    FOREIGN KEY (driver_id) REFERENCES driver (id),
    call_sign                     integer,
    driver_company                varchar,
    driver_company_reg_number     varchar,
    driver_company_address        varchar,
    firm_id                       integer,
    FOREIGN KEY (firm_id) REFERENCES firm (id),
    firm_name                     varchar,
    reg_number                    varchar,
    vat_number                    varchar,
    iban                          varchar,
    bank                          varchar,
    invoice_number                varchar,
    week_number                   integer,
    date_creation                 date,
    date_stamp                    date,
    rent                          bigint,
    frs_connection_fee            bigint,
    issued_in_cash                bigint,
    bank_transfer                 bigint,
    auto_repair                   bigint,
    self_responsibility           bigint,
    other_negative                bigint,
    bank_transfer_from_bolt       bigint,
    bank_transfer_from_car_renter bigint,
    frs_rsk                       bigint,
    cash_from_renter              bigint,
    bonus_frs                     bigint,
    bonus_bolt                    bigint,
    discount                      bigint,
    other_positive                bigint,
    comment                       varchar
);

